### ISSUE TITLE
OSS Gate Workshoptokyo2019-07-27g9m8kqhskjrfroots/bedrockWork log

### ISSUE THREAD

**Issue by ryomo56** [oss-gate/workshop#1223]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by pocke** [comment]
よろしくおねがいします！！

**Comment by g9m8kqhskjrf** [comment]
roots/bedrockというプロジェクトを選びます。

**Comment by g9m8kqhskjrf** [comment]
ライセンスを確認し、OKでした。
https://github.com/roots/bedrock/blob/master/LICENSE.md

**Comment by g9m8kqhskjrf** [comment]
readmeを読んでdockerfileに組み込みました。

**Comment by g9m8kqhskjrf** [comment]
readmeを読み、dockerfileに組み込みました。
https://github.com/roots/bedrock/blob/master/README.md

`FROM php:7.3.7-apache

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer && \
    apt update && \
    docker-php-ext-install pdo_mysql mysqli mbstring && \
    apt install zip unzip && \
    apt install -y procps && \
    composer create-project roots/bedrock && \
    chown www-data:www-data -R /var/www/html/bedrock && \
    useradd -m test && \
    su test

EXPOSE 80
`

**Comment by g9m8kqhskjrf** [comment]
docker-compose.ymlを作成しました。

`version: "2"
services:
  apache-bedrock5:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./bedrock:/var/www/html/bedrock:rw
      - ./etc:/etc/apache2
    environment:
      VIRTUAL_HOST: example.com
      WORDPRESS_DB_PASSWORD: root
      CERT_NAME: default
    depends_on:
      - bedrockmysql
    restart: always
    tty: true
    logging:
      options:
        max-size: 5m
        max-file: "10"

  bedrockmysql:
    image: mysql:5.7
    volumes:
            - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

networks:
  default:
    external:
      name: shared`

**Comment by g9m8kqhskjrf** [comment]
サイトにアクセスできなかったので調査しました。
URLを変更してテスト。
apacheのバーチャルホストのURLとdocker-compose.ymlのURLを合わせました。

**Comment by g9m8kqhskjrf** [comment]
macのhostsを設定しました。

0.0.0.0 example.com

**Comment by g9m8kqhskjrf** [comment]
example.comにアクセスすると
エラーが出たので調査したところ
dockerコンテナのapacheのバーチャルホスト設定が違っていたので修正した。
（過去の設定が残っていた部分があった）

**Comment by g9m8kqhskjrf** [comment]
.envファイル（bedrock設定ファイル）とapacheのconfファイルのアドレス部分を修正した。

**Comment by g9m8kqhskjrf** [comment]
インストール画面が表示された。

**Comment by g9m8kqhskjrf** [comment]
wordpressで新規投稿をする
↓
パーマリンク をtitle名に変更する
↓
もう一度新規投稿をすると失敗する。

**Comment by pocke** [comment]
https://www.clear-code.com/blog/2019/7/12.html

英語でフィードバックをするのに参考にどうぞ！
箇条書きで書くのは良い手段だと思います！

**Comment by pocke** [comment]
GitHubリポジトリのCommunityページを見ると、参考になる情報が乗っていそう、という話をしました。
https://github.com/roots/bedrock/community

**Comment by g9m8kqhskjrf** [comment]
参考URLありがとうございます！

**Comment by g9m8kqhskjrf** [comment]
issue書いてみました。お時間のある時にツッコミをお願いいたします。

**Comment by g9m8kqhskjrf** [comment]
#Description
New post fails after changing permalink
 
#Steps to reproduce 1docker-compose.yml
version: "2"
services:
  apache-bedrock5:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./bedrock:/var/www/html/bedrock:rw
      - ./etc:/etc/apache2
    environment:
      VIRTUAL_HOST: example.com
      WORDPRESS_DB_PASSWORD: root
      CERT_NAME: default
    depends_on:
      - bedrockmysql
    restart: always
    tty: true
    logging:
      options:
        max-size: 5m
        max-file: "10"

  bedrockmysql:
    image: mysql:5.7
    volumes:
            - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

networks:
  default:
    external:
      name: shared
 
2Dockerfile
FROM php:7.3.7-apache

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer && \
    apt update && \
    docker-php-ext-install pdo_mysql mysqli mbstring && \
    apt install zip unzip && \
    apt install -y procps && \
    composer create-project roots/bedrock && \
    chown www-data:www-data -R /var/www/html/bedrock

EXPOSE 80
  
3.env
#DB_NAME=bedrockmysql
#DB_USER=root
#DB_PASSWORD=root

# Optionally, you can use a data source name (DSN)
# When using a DSN, you can remove the DB_NAME, DB_USER, DB_PASSWORD, and DB_HOST variables
# DATABASE_URL=mysql://database_user:database_password@database_host:database_port/database_name
DATABASE_URL=mysql://root:root@172.20.0.3:3306/bedrockmysql

# Optional variables
#DB_HOST=bedrockmysql:3306
#DB_PREFIX=wp_

#WP_ENV=newsun
#I modified
WP_HOME=https://example.com
WP_SITEURL=${WP_HOME}/wp

# Generate your keys here: https://roots.io/salts.html
AUTH_KEY='m*iC1=K`@pXo[B/R&-;A_o2Qbe3@j$Q[u5!_uMC[NH9G0<*3BNl[iqg&LnBoM,b)'
SECURE_AUTH_KEY='NOR_d#Z@tOLrB*&]X>T(h=/5&WIy7+Zt|lUloN4|pG>o}:B=X[x3qeX4,Ps*PCd9'
LOGGED_IN_KEY='jO2kPk_=G(;bj[W$F7e+[R?7X*c/Xt$6qd$2#;7DCHWkBJ84w<OMK<C]]2_BjaIn'
NONCE_KEY='stliN3Gbs_CLd)oEV^n,2XJAvVvD?Gkhz^V+18eCMyr*n]lzAfsXZ1@BK$@UxK*4'
AUTH_SALT='_+dxmSL4N<+{2/?$6eakp^cEx2=7fwR1*A>Mto}<-=6@N9|Gu-)b}Z6!`Kx%3UdH'
SECURE_AUTH_SALT=';zMHLk5`AP.OdtfJxz7Hfp}DfWrWK`Br`u>l,8cTTGnxK^p883*a+ZyY@</v,r:X'
LOGGED_IN_SALT='a!b}@J|Jy[YRrZ2YQPYdsP(2M-JvX?w?FwLUJ@4gI5(c0qzypn!EE&cDi]rG}Dg6'
NONCE_SALT='Y`R3hPJ<D+;rNI#s4#{zN+NL9u2t((>tnY$Vo@aMkdhq<$@d+w%0W?o;Ec_J20rk'  
4docker-compose up -d --build
 
5コンテナが立ち上がる  6Install WordPress 
wp/wp-admin/post.php  
7Post published
wp/wp-admin/post.php
 
8Changing permalink to Post name wp/wp-admin/options-permalink.php  
9Post published again
 
10Publishing failed
 
#Expected behavior I want to use 'post name' for posting new note  #Actual behavior
Publishing failed
 
#What I want to ask you
I have not identified the cause. if you need more information, feel free to ask me.

**Comment by g9m8kqhskjrf** [comment]
* [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

[Description of the issue]

## Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by g9m8kqhskjrf** [comment]
https://github.com/roots/bedrock/issues/453

**Comment by g9m8kqhskjrf** [comment]
その後コミッターの方から返信がありました！
[roots/bedrock#453](https://github.com/roots/bedrock/issues/453)

**Comment by g9m8kqhskjrf** [comment]
その後自分でも少し気になったことを書きます。

通常のwordpressコンテナでも同様の問題が発生し
.htaccessに以下を設定したら問題が改善しました。

`<Directory /var/www/html>
            AllowOverride All
`

**Comment by g9m8kqhskjrf** [comment]
bedrockでも同様に設定をしてみましたが
問題は改善しませんでした。

```

<Directory /var/www/html/bedrock/web>
            AllowOverride All

```

```

<Directory /var/www/html/bedrock>
            AllowOverride All

```

```

<Directory /var/www/html>
            AllowOverride All

```
